import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo List Pwa',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {apple: '/icon.png'},
  themeColor: '#DAF2D6'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='min-h-screen w-full overflow-hidden relative'>
          {children}
        </main>
      </body>
    </html>
  )
}
